name: V2RayN Subscription Filter & Save

on:
  workflow_dispatch:
    inputs:
      subscription:
        description: 'Base64 Encoded Subscription'
        required: true
        type: string

jobs:
  process-subscription:
    runs-on: ubuntu-latest
    outputs:
      filtered_subscription: ${{ steps.filter.outputs.result }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # 确保克隆仓库代码

      - name: Decode Subscription
        id: decode
        run: |
          echo "::set-output name=decoded::$(echo -n "$SUBSCRIPTION" | base64 --decode)"
        env:
          SUBSCRIPTION: ${{ github.event.inputs.subscription }}

      - name: Filter Nodes and Save File
        id: filter
        run: |
          filtered=$(echo "$INPUT" | grep -v '^hysteria2://')
          echo -n "$filtered" | base64 -w0 > filtered_subscription.txt
          echo "::set-output name=result::$(cat filtered_subscription.txt)"
        env:
          INPUT: ${{ steps.decode.outputs.decoded }}

      - name: Upload Filtered File
        uses: actions/upload-artifact@v4
        with:
          name: filtered-subscription
          path: filtered_subscription.txt

      - name: Commit and Push Filtered File
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 配置 Git 远程（使用 GITHUB_TOKEN 授权）
          git config --global user.email "q2891362919@163.com"
          git config --global user.name "DSLZL"
          git remote set-url origin https://x-access-token:${REPO_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

          # 添加文件并提交
          git add filtered_subscription.txt
          git commit -m "Auto filtered subscription" || echo "No changes to commit"

          # 推送到目标分支（默认 main）
          git push origin ${{ github.ref }}